### ISSUE TITLE
Information about number of parallel PouchDB instances

### ISSUE THREAD

**Issue by hadrien-toma** [redgeoff/couchdb-howler#111]
Hello @redgeoff, I got in this repo through the stackoverflow issue [Maximum number of live replications in PouchDB](https://stackoverflow.com/questions/48099582/maximum-number-of-live-replications-in-pouchdb).

This project seems interesting, would you answer me few questions in order to investigate more on using Howler?
- How many PouchDB changes feeds are finally listenable on the client side? If I need for approximately 500 changes listeners, do you think Howler could fit it?
- Do you use Howler in production?

In any case, great initiative and idea here, thank you for this work and for sharing it.

**Comment by hadrien-toma** [comment]
Update: same question replacing PouchDB by Slouch :heart_eyes:

**Comment by redgeoff** [comment]
couchdb-howler should be capable of allowing a client to listen to any number of CouchDB databases. Feasibly, I'd suspect that it could handle hundreds of thousands or millions, but this hasn't been tested. The breaking point would be the number of connection records the server can store in memory, but this should be a lot as these records are very tiny.

**Comment by hadrien-toma** [comment]
Awesome, I can't wait to try Slouch :yum:. Thank you for your answer!
