### ISSUE TITLE
Question: Using with React Native

### ISSUE THREAD

**Issue by ephopper** [redgeoff/couchdb-howler#51]
Hi @redgeoff ,
Just doing some initial tests with howler client side in React Native and I'm getting the below error:

```
Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
```
along with a long, pretty much useless, stack trace that RN returns with only native modules, so there is no indication of where the error is actually occurring. 

I was just wondering if you have (successfully) used howler with RN.

Thanks!

**Comment by redgeoff** [comment]
I have not, but in my experience with RN, that type of error occurs when you try to output an object instead of a string in your JSX.

**Comment by ephopper** [comment]
Yeah, it's being caused buy `import Client from 'couchdb-howler';` but the error that is returned doesn't provide any useful information as to where specifically it is coming from - that's more of a RN thing though.

Thanks!
